<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Magento Web API Functional Tests" tests="31" assertions="151" errors="26" failures="1" skipped="0" time="9.542014">
    <testsuite name="Magestore\Webpos\Api\Cart\CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" tests="6" assertions="0" errors="6" failures="0" skipped="0" time="0.001330">
      <testcase name="testSaveCart" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="291" assertions="0" time="0.000384">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveCart
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
      <testcase name="testSaveQuoteData" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="337" assertions="0" time="0.000211">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveQuoteData
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
      <testcase name="testSaveShippingMethod" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="410" assertions="0" time="0.000169">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveShippingMethod
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
      <testcase name="testPlaceOrder" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="468" assertions="0" time="0.000190">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testPlaceOrder
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
      <testcase name="testApplyGiftcard" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="612" assertions="0" time="0.000173">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testApplyGiftcard
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
      <testcase name="testSpendPoint" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="640" assertions="0" time="0.000203">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSpendPoint
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\CategoryRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.002913">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\CategoryRepositoryTest" classname="Magestore.Webpos.Api.Catalog.CategoryRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php" line="35" assertions="0" time="0.002913">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\CategoryRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\CategoryInterface" for "Magestore\Webpos\Api\Catalog\Constraint\CategoryRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000565">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" classname="Magestore.Webpos.Api.Catalog.ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" line="36" assertions="0" time="0.000320">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\ProductRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\ProductInterface" for "Magestore\Webpos\Api\Catalog\Constraint\ProductRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php:30
</error>
      </testcase>
      <testcase name="testGetOptions" class="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" classname="Magestore.Webpos.Api.Catalog.ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" line="87" assertions="0" time="0.000245">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\ProductRepositoryTest::testGetOptions
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\ProductInterface" for "Magestore\Webpos\Api\Catalog\Constraint\ProductRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php:30
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\SwatchRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000389">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\SwatchRepositoryTest" classname="Magestore.Webpos.Api.Catalog.SwatchRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php" line="35" assertions="0" time="0.000389">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\SwatchRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\SwatchInterface" for "Magestore\Webpos\Api\Catalog\Constraint\SwatchRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Checkout\CartTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="6.104458">
      <testcase name="testSendEmail" class="Magestore\Webpos\Api\Checkout\CartTest" classname="Magestore.Webpos.Api.Checkout.CartTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php" line="24" assertions="0" time="6.104458">
        <error type="Exception">Magestore\Webpos\Api\Checkout\CartTest::testSendEmail
Exception: {"message":"The order #WP11513741610113 cannot be sent to the customer lionel123@gmail.com"}

/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php:38
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Checkout\TaxClassTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/TaxClassTest.php" tests="1" assertions="6" errors="0" failures="0" skipped="0" time="1.884573">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Checkout\TaxClassTest" classname="Magestore.Webpos.Api.Checkout.TaxClassTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/TaxClassTest.php" line="24" assertions="6" time="1.884573"/>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Config\ConfigRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Config/ConfigRepositoryTest.php" tests="1" assertions="142" errors="0" failures="0" skipped="0" time="0.602583">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Config\ConfigRepositoryTest" classname="Magestore.Webpos.Api.Config.ConfigRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Config/ConfigRepositoryTest.php" line="24" assertions="142" time="0.602583"/>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\CurrentSessionId\CurrentSessionIdTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/CurrentSessionId/CurrentSessionIdTest.php" tests="1" assertions="0" errors="0" failures="1" skipped="0" time="0.000613">
      <testcase name="Warning" assertions="0" time="0.000613">
        <warning type="PHPUnit\Framework\Warning">Warning
No tests found in class "Magestore\Webpos\Api\CurrentSessionId\CurrentSessionIdTest".

</warning>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000631">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" classname="Magestore.Webpos.Api.Customer.CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" line="35" assertions="0" time="0.000343">
        <error type="RuntimeException">Magestore\Webpos\Api\Customer\CustomerRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Customer\Constraint\CustomerInterface" for "Magestore\Webpos\Api\Customer\Constraint\CustomerRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php:29
</error>
      </testcase>
      <testcase name="testSave" class="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" classname="Magestore.Webpos.Api.Customer.CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" line="83" assertions="0" time="0.000288">
        <error type="RuntimeException">Magestore\Webpos\Api\Customer\CustomerRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Customer\Constraint\CustomerInterface" for "Magestore\Webpos\Api\Customer\Constraint\CustomerRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Inventory\StockItemRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Inventory/StockItemRepositoryTest.php" tests="1" assertions="1" errors="0" failures="0" skipped="0" time="0.335855">
      <testcase name="testGetStockItems" class="Magestore\Webpos\Api\Inventory\StockItemRepositoryTest" classname="Magestore.Webpos.Api.Inventory.StockItemRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Inventory/StockItemRepositoryTest.php" line="24" assertions="1" time="0.335855"/>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Payment\PaymentRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000353">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Payment\PaymentRepositoryTest" classname="Magestore.Webpos.Api.Payment.PaymentRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php" line="35" assertions="0" time="0.000353">
        <error type="RuntimeException">Magestore\Webpos\Api\Payment\PaymentRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Payment\Constraint\PaymentInterface" for "Magestore\Webpos\Api\Payment\Constraint\PaymentRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Pos\PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000632">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Pos\PosRepositoryTest" classname="Magestore.Webpos.Api.Pos.PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" line="44" assertions="0" time="0.000345">
        <error type="RuntimeException">Magestore\Webpos\Api\Pos\PosRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Pos\Constraint\PosInterface" for "Magestore\Webpos\Api\Pos\Constraint\PosRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php:36
</error>
      </testcase>
      <testcase name="testAssignStaff" class="Magestore\Webpos\Api\Pos\PosRepositoryTest" classname="Magestore.Webpos.Api.Pos.PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" line="112" assertions="0" time="0.000287">
        <error type="RuntimeException">Magestore\Webpos\Api\Pos\PosRepositoryTest::testAssignStaff
RuntimeException: Source class "\Magestore\Webpos\Api\Pos\Constraint\PosInterface" for "Magestore\Webpos\Api\Pos\Constraint\PosRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php:36
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000347">
      <testcase name="testSaveCreditmemo" class="Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest" classname="Magestore.Webpos.Api.Sales.CreditmemoRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php" line="35" assertions="0" time="0.000347">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest::testSaveCreditmemo
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\CreditmemoInterface" for "Magestore\Webpos\Api\Sales\Constraint\CreditmemoRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.450436">
      <testcase name="testUpdateQty" class="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" classname="Magestore.Webpos.Api.Sales.InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" line="36" assertions="0" time="0.151155">
        <error type="Exception">Magestore\Webpos\Api\Sales\InvoiceRepositoryTest::testUpdateQty
Exception: {"message":"Invalid type for value: \"WP11513743849738\". Expected Type: \"int\"."}

/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php:66
</error>
      </testcase>
      <testcase name="testSaveInvoice" class="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" classname="Magestore.Webpos.Api.Sales.InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" line="79" assertions="0" time="0.299281">
        <error type="Exception">Magestore\Webpos\Api\Sales\InvoiceRepositoryTest::testSaveInvoice
Exception: {"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5a71625d41ae3"}

/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php:154
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000651">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Sales\OrderRepositoryTest" classname="Magestore.Webpos.Api.Sales.OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" line="35" assertions="0" time="0.000344">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\OrderRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\OrderInterface" for "Magestore\Webpos\Api\Sales\Constraint\OrderRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php:29
</error>
      </testcase>
      <testcase name="testAddComment" class="Magestore\Webpos\Api\Sales\OrderRepositoryTest" classname="Magestore.Webpos.Api.Sales.OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" line="142" assertions="0" time="0.000307">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\OrderRepositoryTest::testAddComment
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\OrderInterface" for "Magestore\Webpos\Api\Sales\Constraint\OrderRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php:29
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000403">
      <testcase name="testSave" class="Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest" classname="Magestore.Webpos.Api.Shift.CashTransactionRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php" line="41" assertions="0" time="0.000403">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\CashTransactionInterface" for "Magestore\Webpos\Api\Shift\Constraint\CashTransactionRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php:35
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" tests="4" assertions="0" errors="4" failures="0" skipped="0" time="0.001575">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="49" assertions="0" time="0.000606">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
</error>
      </testcase>
      <testcase name="testSave" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="160" assertions="0" time="0.000320">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
</error>
      </testcase>
      <testcase name="testValidateSession" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="192" assertions="0" time="0.000331">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testValidateSession
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
</error>
      </testcase>
      <testcase name="testOpenSession" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="322" assertions="0" time="0.000318">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testOpenSession
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Staff\StaffManagementTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Staff/StaffManagementTest.php" tests="1" assertions="2" errors="0" failures="0" skipped="0" time="0.153708">
      <testcase name="testStaffLogin" class="Magestore\Webpos\Api\Staff\StaffManagementTest" classname="Magestore.Webpos.Api.Staff.StaffManagementTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Staff/StaffManagementTest.php" line="31" assertions="2" time="0.153708"/>
    </testsuite>
  </testsuite>
</testsuites>
