<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Magento Web API Functional Tests" tests="31" assertions="0" errors="30" failures="1" skipped="0" time="7.242832">
    <testsuite name="Magestore\Webpos\Api\Cart\CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" tests="6" assertions="0" errors="6" failures="0" skipped="0" time="0.001464">
      <testcase name="testSaveCart" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="291" assertions="0" time="0.000594">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveCart
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSaveQuoteData" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="337" assertions="0" time="0.000161">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveQuoteData
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSaveShippingMethod" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="410" assertions="0" time="0.000164">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSaveShippingMethod
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testPlaceOrder" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="468" assertions="0" time="0.000200">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testPlaceOrder
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testApplyGiftcard" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="612" assertions="0" time="0.000168">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testApplyGiftcard
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSpendPoint" class="Magestore\Webpos\Api\Cart\CheckoutTest" classname="Magestore.Webpos.Api.Cart.CheckoutTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php" line="640" assertions="0" time="0.000177">
        <error type="ReflectionException">Magestore\Webpos\Api\Cart\CheckoutTest::testSpendPoint
ReflectionException: Class Magestore\Webpos\Api\Cart\Constraint\Checkout does not exist

/var/www/vendor/magento/framework/Code/Reader/ClassReader.php:19
/var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php:44
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Cart/CheckoutTest.php:43
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\CategoryRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.002820">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\CategoryRepositoryTest" classname="Magestore.Webpos.Api.Catalog.CategoryRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php" line="35" assertions="0" time="0.002820">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\CategoryRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\CategoryInterface" for "Magestore\Webpos\Api\Catalog\Constraint\CategoryRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/CategoryRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000533">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" classname="Magestore.Webpos.Api.Catalog.ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" line="36" assertions="0" time="0.000294">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\ProductRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\ProductInterface" for "Magestore\Webpos\Api\Catalog\Constraint\ProductRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php:30
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testGetOptions" class="Magestore\Webpos\Api\Catalog\ProductRepositoryTest" classname="Magestore.Webpos.Api.Catalog.ProductRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php" line="87" assertions="0" time="0.000239">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\ProductRepositoryTest::testGetOptions
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\ProductInterface" for "Magestore\Webpos\Api\Catalog\Constraint\ProductRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/ProductRepositoryTest.php:30
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Catalog\SwatchRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000332">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Catalog\SwatchRepositoryTest" classname="Magestore.Webpos.Api.Catalog.SwatchRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php" line="35" assertions="0" time="0.000332">
        <error type="RuntimeException">Magestore\Webpos\Api\Catalog\SwatchRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Catalog\Constraint\SwatchInterface" for "Magestore\Webpos\Api\Catalog\Constraint\SwatchRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Catalog/SwatchRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Checkout\CartTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="5.117602">
      <testcase name="testSendEmail" class="Magestore\Webpos\Api\Checkout\CartTest" classname="Magestore.Webpos.Api.Checkout.CartTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php" line="24" assertions="0" time="5.117602">
        <error type="Exception">Magestore\Webpos\Api\Checkout\CartTest::testSendEmail
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 1172005053040&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/CartTest.php:38
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Checkout\TaxClassTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/TaxClassTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="1.514709">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Checkout\TaxClassTest" classname="Magestore.Webpos.Api.Checkout.TaxClassTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/TaxClassTest.php" line="24" assertions="0" time="1.514709">
        <error type="Exception">Magestore\Webpos\Api\Checkout\TaxClassTest::testGetList
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 545012713090&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:51
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:95
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Checkout/TaxClassTest.php:40
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Config\ConfigRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Config/ConfigRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.125884">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Config\ConfigRepositoryTest" classname="Magestore.Webpos.Api.Config.ConfigRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Config/ConfigRepositoryTest.php" line="24" assertions="0" time="0.125884">
        <error type="Exception">Magestore\Webpos\Api\Config\ConfigRepositoryTest::testGetList
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 1093061708906&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:51
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:95
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Config/ConfigRepositoryTest.php:33
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\CurrentSessionId\CurrentSessionIdTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/CurrentSessionId/CurrentSessionIdTest.php" tests="1" assertions="0" errors="0" failures="1" skipped="0" time="0.000631">
      <testcase name="Warning" assertions="0" time="0.000631">
        <warning type="PHPUnit\Framework\Warning">Warning
No tests found in class "Magestore\Webpos\Api\CurrentSessionId\CurrentSessionIdTest".

/var/www/vendor/phpunit/phpunit/phpunit:53
</warning>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000575">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" classname="Magestore.Webpos.Api.Customer.CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" line="35" assertions="0" time="0.000334">
        <error type="RuntimeException">Magestore\Webpos\Api\Customer\CustomerRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Customer\Constraint\CustomerInterface" for "Magestore\Webpos\Api\Customer\Constraint\CustomerRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSave" class="Magestore\Webpos\Api\Customer\CustomerRepositoryTest" classname="Magestore.Webpos.Api.Customer.CustomerRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php" line="83" assertions="0" time="0.000241">
        <error type="RuntimeException">Magestore\Webpos\Api\Customer\CustomerRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Customer\Constraint\CustomerInterface" for "Magestore\Webpos\Api\Customer\Constraint\CustomerRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Customer/CustomerRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Inventory\StockItemRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Inventory/StockItemRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.122027">
      <testcase name="testGetStockItems" class="Magestore\Webpos\Api\Inventory\StockItemRepositoryTest" classname="Magestore.Webpos.Api.Inventory.StockItemRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Inventory/StockItemRepositoryTest.php" line="24" assertions="0" time="0.122027">
        <error type="Exception">Magestore\Webpos\Api\Inventory\StockItemRepositoryTest::testGetStockItems
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 1033854200127&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:51
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:95
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Inventory/StockItemRepositoryTest.php:50
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Payment\PaymentRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000306">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Payment\PaymentRepositoryTest" classname="Magestore.Webpos.Api.Payment.PaymentRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php" line="35" assertions="0" time="0.000306">
        <error type="RuntimeException">Magestore\Webpos\Api\Payment\PaymentRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Payment\Constraint\PaymentInterface" for "Magestore\Webpos\Api\Payment\Constraint\PaymentRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Payment/PaymentRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Pos\PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000644">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Pos\PosRepositoryTest" classname="Magestore.Webpos.Api.Pos.PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" line="44" assertions="0" time="0.000363">
        <error type="RuntimeException">Magestore\Webpos\Api\Pos\PosRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Pos\Constraint\PosInterface" for "Magestore\Webpos\Api\Pos\Constraint\PosRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php:36
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testAssignStaff" class="Magestore\Webpos\Api\Pos\PosRepositoryTest" classname="Magestore.Webpos.Api.Pos.PosRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php" line="112" assertions="0" time="0.000281">
        <error type="RuntimeException">Magestore\Webpos\Api\Pos\PosRepositoryTest::testAssignStaff
RuntimeException: Source class "\Magestore\Webpos\Api\Pos\Constraint\PosInterface" for "Magestore\Webpos\Api\Pos\Constraint\PosRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Pos/PosRepositoryTest.php:36
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000328">
      <testcase name="testSaveCreditmemo" class="Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest" classname="Magestore.Webpos.Api.Sales.CreditmemoRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php" line="35" assertions="0" time="0.000328">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\CreditmemoRepositoryTest::testSaveCreditmemo
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\CreditmemoInterface" for "Magestore\Webpos\Api\Sales\Constraint\CreditmemoRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/CreditmemoRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.235632">
      <testcase name="testUpdateQty" class="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" classname="Magestore.Webpos.Api.Sales.InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" line="36" assertions="0" time="0.115954">
        <error type="Exception">Magestore\Webpos\Api\Sales\InvoiceRepositoryTest::testUpdateQty
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 1480187732351&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php:66
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSaveInvoice" class="Magestore\Webpos\Api\Sales\InvoiceRepositoryTest" classname="Magestore.Webpos.Api.Sales.InvoiceRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php" line="79" assertions="0" time="0.119678">
        <error type="Exception">Magestore\Webpos\Api\Sales\InvoiceRepositoryTest::testSaveInvoice
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 267192862489&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/CurrentSessionId/CurrentSessionIdTest.php:47
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/InvoiceRepositoryTest.php:80
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Sales\OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" tests="2" assertions="0" errors="2" failures="0" skipped="0" time="0.000542">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Sales\OrderRepositoryTest" classname="Magestore.Webpos.Api.Sales.OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" line="35" assertions="0" time="0.000298">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\OrderRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\OrderInterface" for "Magestore\Webpos\Api\Sales\Constraint\OrderRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testAddComment" class="Magestore\Webpos\Api\Sales\OrderRepositoryTest" classname="Magestore.Webpos.Api.Sales.OrderRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php" line="142" assertions="0" time="0.000244">
        <error type="RuntimeException">Magestore\Webpos\Api\Sales\OrderRepositoryTest::testAddComment
RuntimeException: Source class "\Magestore\Webpos\Api\Sales\Constraint\OrderInterface" for "Magestore\Webpos\Api\Sales\Constraint\OrderRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Sales/OrderRepositoryTest.php:29
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.000371">
      <testcase name="testSave" class="Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest" classname="Magestore.Webpos.Api.Shift.CashTransactionRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php" line="41" assertions="0" time="0.000371">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\CashTransactionRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\CashTransactionInterface" for "Magestore\Webpos\Api\Shift\Constraint\CashTransactionRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/CashTransactionRepositoryTest.php:35
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" tests="4" assertions="0" errors="4" failures="0" skipped="0" time="0.001460">
      <testcase name="testGetList" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="49" assertions="0" time="0.000580">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testGetList
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testSave" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="160" assertions="0" time="0.000305">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testSave
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testValidateSession" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="192" assertions="0" time="0.000279">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testValidateSession
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
      <testcase name="testOpenSession" class="Magestore\Webpos\Api\Shift\ShiftRepositoryTest" classname="Magestore.Webpos.Api.Shift.ShiftRepositoryTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php" line="322" assertions="0" time="0.000296">
        <error type="RuntimeException">Magestore\Webpos\Api\Shift\ShiftRepositoryTest::testOpenSession
RuntimeException: Source class "\Magestore\Webpos\Api\Shift\Constraint\ShiftInterface" for "Magestore\Webpos\Api\Shift\Constraint\ShiftRepository" generation does not exist.

/var/www/vendor/magento/framework/Code/Generator.php:185
/var/www/vendor/magento/framework/Code/Generator.php:112
/var/www/vendor/magento/framework/Code/Generator/Autoloader.php:35
/var/www/vendor/magento/framework/ObjectManager/Relations/Runtime.php:38
/var/www/vendor/magento/framework/Interception/Config/Config.php:166
/var/www/vendor/magento/framework/Interception/Config/Config.php:189
/var/www/vendor/magento/framework/Interception/ObjectManager/Config/Developer.php:61
/var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:47
/var/www/vendor/magento/framework/ObjectManager/ObjectManager.php:70
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Shift/ShiftRepositoryTest.php:35
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
    <testsuite name="Magestore\Webpos\Api\Staff\StaffManagementTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Staff/StaffManagementTest.php" tests="1" assertions="0" errors="1" failures="0" skipped="0" time="0.116973">
      <testcase name="testStaffLogin" class="Magestore\Webpos\Api\Staff\StaffManagementTest" classname="Magestore.Webpos.Api.Staff.StaffManagementTest" file="/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Staff/StaffManagementTest.php" line="31" assertions="0" time="0.116973">
        <error type="Exception">Magestore\Webpos\Api\Staff\StaffManagementTest::testStaffLogin
Exception: &lt;!doctype html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml" &gt;
&lt;head&gt;
    &lt;title&gt;There has been an error processing your request&lt;/title&gt;
    &lt;base href="http://magento2.travis/pub/errors/default/" /&gt;
    &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" /&gt;
    &lt;meta name="robots" content="*"/&gt;
    &lt;link rel="stylesheet" href="css/styles.css" type="text/css" /&gt;
    &lt;link rel="icon" href="images/favicon.ico" type="image/x-icon" /&gt;
    &lt;link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;main class="page-main"&gt;
        
&lt;h1&gt;There has been an error processing your request&lt;/h1&gt;

&lt;div class="trace-container"&gt;
    &lt;div class="trace"&gt;
        &lt;pre&gt;Can't create directory /var/www/generated/code/Magento/Webapi/Controller/Rest/Router/. in [Magento\Webapi\Controller\Rest\Router\Proxy]&lt;/pre&gt;
    &lt;/div&gt;
&lt;/div&gt;
    &lt;p&gt;Error log record number: 1173523198006&lt;/p&gt;
    &lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;


/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:216
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:134
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/CurlClient.php:66
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:98
/var/www/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:175
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/CurrentSessionId/CurrentSessionIdTest.php:47
/var/www/dev/tests/api-functional/testsuite/Magestore/Webpos/Api/Staff/StaffManagementTest.php:33
/var/www/vendor/phpunit/phpunit/phpunit:53
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
